//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiskUsage.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiskUsage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string abtou {
            get {
                return ResourceManager.GetString("abtou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        public static string auto {
            get {
                return ResourceManager.GetString("auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 btnOpen 的本地化字符串。
        /// </summary>
        public static string btnOpen {
            get {
                return ResourceManager.GetString("btnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count 的本地化字符串。
        /// </summary>
        public static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load 的本地化字符串。
        /// </summary>
        public static string load {
            get {
                return ResourceManager.GetString("load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remainder 的本地化字符串。
        /// </summary>
        public static string remainder {
            get {
                return ResourceManager.GetString("remainder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Scan 的本地化字符串。
        /// </summary>
        public static string scan {
            get {
                return ResourceManager.GetString("scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select A Folder 的本地化字符串。
        /// </summary>
        public static string select_a_folder {
            get {
                return ResourceManager.GetString("select a folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        public static string sizeMode_Auto {
            get {
                return ResourceManager.GetString("sizeMode_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kb 的本地化字符串。
        /// </summary>
        public static string sizeMode_Kb {
            get {
                return ResourceManager.GetString("sizeMode_Kb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mb 的本地化字符串。
        /// </summary>
        public static string sizeMode_Mb {
            get {
                return ResourceManager.GetString("sizeMode_Mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disk Usage 的本地化字符串。
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
